# Generated by Django 5.1.3 on 2024-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='flavor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='icecreamtype',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
